spring:
  profiles:
    active:
    - dog
    - EN
    - prod
michiel:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

#  --- creates a new config file
---
spring:
  profiles: prod
michiel:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl

